# Site settings
title: Simplified Trade
email: sales@simplifiedtrade.com
url: http://www.simplifiedtrade.com
description: "We are a Software as a Service (SaaS) start-up focused on consumer package goods and grocery forecasting and marketing"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Simplified Trade

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#social:
#  - title: twitter
#    url: https://twitter.com/_simple_trade

# Build settings
markdown: kramdown
permalink: pretty
